name: msc-presentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - livereload==2.6.*
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyterlab
  - black
  - pooch
  - verde
  - harmonica
  - ensaio
  - pip
  # Things that need to come from pip
  - pip:
    - black[jupyter]
    - git+https://github.com/fatiando/magali